-- MySQL Script generated by MySQL Workbench
-- Mon Sep 10 08:21:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stores
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stores` ;

-- -----------------------------------------------------
-- Schema stores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stores` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stores` ;

-- -----------------------------------------------------
-- Table `stores`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stores`.`department` ;

CREATE TABLE IF NOT EXISTS `stores`.`department` (
  `dept_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dept_id`),
  UNIQUE INDEX `dept_id_UNIQUE` (`dept_id` ASC),
  UNIQUE INDEX `dept_name_UNIQUE` (`dept_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stores`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stores`.`category` ;

CREATE TABLE IF NOT EXISTS `stores`.`category` (
  `cat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NOT NULL,
  `dpt_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cat_id`),
  INDEX `dpt_id_idx` (`dpt_id` ASC),
  CONSTRAINT `dpt_id`
    FOREIGN KEY (`dpt_id`)
    REFERENCES `stores`.`department` (`dept_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stores`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stores`.`location` ;

CREATE TABLE IF NOT EXISTS `stores`.`location` (
  `loc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `loc_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`loc_id`),
  UNIQUE INDEX `loc_name_UNIQUE` (`loc_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Locations data';


-- -----------------------------------------------------
-- Table `stores`.`dept_locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stores`.`dept_locations` ;

CREATE TABLE IF NOT EXISTS `stores`.`dept_locations` (
  `location_id` INT(11) NOT NULL,
  `deptartment_id` INT(11) NOT NULL,
  INDEX `location_id_idx` (`location_id` ASC),
  INDEX `deptartment_id_idx` (`deptartment_id` ASC),
  CONSTRAINT `deptartment_id`
    FOREIGN KEY (`deptartment_id`)
    REFERENCES `stores`.`department` (`dept_id`),
  CONSTRAINT `loc_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `stores`.`location` (`loc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stores`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stores`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `stores`.`subcategory` (
  `subcat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `subcat_name` VARCHAR(45) NOT NULL,
  `cat_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`subcat_id`),
  INDEX `cat_id_idx` (`cat_id` ASC),
  CONSTRAINT `cat_id`
    FOREIGN KEY (`cat_id`)
    REFERENCES `stores`.`category` (`cat_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
